### PR TITLE
Migrate to casa 6

### PR DESCRIPTION
**Pull request by bennahugo**
Co-authored by @AlecThomson

### CODE REVIEW

**Comment by bennahugo** [comment]
Absolutely beautiful. Remind me to buy you a beer if ever you're in town @AlecThomson. Just saved me a massive headache on how to start testing packages on 3.10 - things did not work well with the distributed monolythic casa 6 because it still ships 3.8 and there is no KERN for this yet...

**Comment by AlecThomson** [comment]
Sounds good to me @bennahugo! Glad to be of assistance.

By the way, I think CASA on Python 3.10 is pretty broken. See https://github.com/casacore/python-casacore/issues/251 for reference

**Comment by bennahugo** [comment]
Yup ran into 3.10 woes myself trying to set CASA up on AWS instances for some teaching -- unfortunately RA is always playing catchup - just not enough hands. It looks like the simulator component is working fine though, so I'm going to say this is working for now.

I will try and push a simms release soon.

**Comment by bennahugo** [comment]
@SpheMakh can you please make a release (or give me maintenance access on PyPI)? Thanks

**Pull request merged**
